# 模型配置

model_type: "qwen2-vl"  # qwen2-vl, qwen3-vl, llava
model_id: "Qwen/Qwen2-VL-7B-Instruct"
model_path: "/home/dcy/project/MMUnlearner/models/Qwen/Qwen2-VL-7B-Instruct"
vanilla_path: "/home/dcy/project/MMUnlearner/models/Qwen/Qwen2-VL-7B-Instruct"

# LoRA 配置
lora:
  enable: true
  r: 16
  alpha: 16
  dropout: 0.05
  target_modules: "auto"  # auto 表示自动检测所有线性层
